% BerkeleyAOTumblingEAnalyze
%
% Collect up and analyze output of the calcuations

%% Clear
clear; close all;

%% Parameters
nShifts = 3;
nReplications = 3;
filterModels = {[], 'photocurrentImpulseResponseBased', 'watsonFilter'};
nFilterModels = length(filterModels);

for ss = 1:nShifts
    for rr = 1:nReplications
        for ff = 1:length(filterModels)
            fileSuffix = sprintf('Calcs_posYShift_%d_Rep_%d_filter_%d',ss,rr,ff);

            fileSuffix = sprintf('Calcs_negYShift_%d_Rep_%d_filter_%d',ss,rr,ff);

            fileSuffix = sprintf('Calcs_posXShift_%d_Rep_%d_filter_%d',ss,rr,ff);


            fileSuffix = sprintf('Calcs_negXShift_%d_Rep_%d_filter_%d',ss,rr,ff);

            % Read in output
            
        end
    end
end

% Pos x shift
for ss = 1:nShifts
    jitterMinutes(ss) = jitterRangeMinutes*(rand-0.5);
    for rr = 1:nReplications
        for ff = 1:length(filterModels)
            fprintf('%s\n',fileSuffix);
            [logThreshold(ss,rr,ff), logMAR(ss,rr,ff), questObj{ss,rr,ff}, ...
                psychometricFunction{ss,rr,ff}, fittedPsychometricParamsParams{ss,rr,ff}, ...
                trialByTrialStimulusAlternatives{ss,rr,ff},trialByTrialPerformancePhotocurrent{ss,rr,ff}] = ...
                BerkeleyAOTumblingEThreshold( ...
                'fastParams', false, ...
                'rngSeed', 0, ...
                'chromaSpecification_backgroundRGB', [1 0 0], ...
                'chromaSpecification_foregroundRGB', [0 0 0], ...
                'temporalModulationParams_numFrame', totalFrames, ...
                'temporalModulationParams_xShiftPerFrameMin', theShift{ss}+jitterMinutes(ss), ...
                'temporalModulationParams_yShiftPerFrameMin', zeros(1,totalFrames), ...
                'temporalModulationParams_backgroundRGBPerFrame', backgroundRGBPerFrame, ...
                'temporalModulationParams_stimOnFrames', stimOnFrames, ...
                'temporalModulationParams_frameRateHz', temporalFrequencyHz , ...
                'temporalFilterValues', filterModels{ff}, ...
                'watsonParams_tau', watsonParams_tau, ...
                'minLetterSizeMinutes', letterSizeMinutes , ...
                'maxLetterSizeMinutes', letterSizeMinutes , ...
                'letterSizesNumExamined', 1, ...
                'nTest', nTest, ...
                'useConeContrast', true, ...
                'whichNoisyInstanceNre', 'Gaussian', ...
                'gaussianSigma', noiseSds(ff), ...
                'whichClassifierEngine', 'rceTemplateDistance', ...
                'visualizeScene', true, ...
                'visualizeEsOnMosaic', true, ...
                'visualizeEsWhichFrames', offFramesStart+1, ...
                'fileSuffix', fileSuffix, ...
                'validationThresholds',[]);

                % Thus counts on us only studying one letter size, which is
                % enforced by the options in the call above.
                keys = psychometricFunction{ss,rr,ff}.keys;
                pCorrect(ss,rr,ff) = psychometricFunction{ss,rr,ff}(keys{1});
        end
    end
end

% Neg x shift
for ss = 1:nShifts
    jitterMinutes(ss) = jitterRangeMinutes*(rand-0.5);
    for rr = 1:nReplications
        for ff = 1:length(filterModels)
            fprintf('%s\n',fileSuffix);
            [logThreshold(ss,rr,ff), logMAR(ss,rr,ff), questObj{ss,rr,ff}, ...
                psychometricFunction{ss,rr,ff}, fittedPsychometricParamsParams{ss,rr,ff}, ...
                trialByTrialStimulusAlternatives{ss,rr,ff},trialByTrialPerformancePhotocurrent{ss,rr,ff}] = ...
                BerkeleyAOTumblingEThreshold( ...
                'fastParams', false, ...
                'rngSeed', 0, ...
                'chromaSpecification_backgroundRGB', [1 0 0], ...
                'chromaSpecification_foregroundRGB', [0 0 0], ...
                'temporalModulationParams_numFrame', totalFrames, ...
                'temporalModulationParams_xShiftPerFrameMin', -theShift{ss}+jitterMinutes(ss), ...
                'temporalModulationParams_yShiftPerFrameMin', zeros(1,totalFrames), ...
                'temporalModulationParams_backgroundRGBPerFrame', backgroundRGBPerFrame, ...
                'temporalModulationParams_stimOnFrames', stimOnFrames, ...
                'temporalModulationParams_frameRateHz', temporalFrequencyHz , ...
                'temporalFilterValues', filterModels{ff}, ...
                'watsonParams_tau', watsonParams_tau, ...
                'minLetterSizeMinutes', letterSizeMinutes , ...
                'maxLetterSizeMinutes', letterSizeMinutes , ...
                'letterSizesNumExamined', 1, ...
                'nTest', nTest, ...
                'useConeContrast', true, ...
                'whichNoisyInstanceNre', 'Gaussian', ...
                'gaussianSigma', noiseSds(ff), ...
                'whichClassifierEngine', 'rceTemplateDistance', ...
                'visualizeScene', true, ...
                'visualizeEsOnMosaic', true, ...
                'visualizeEsWhichFrames', offFramesStart+1, ...
                'fileSuffix', fileSuffix, ...
                'validationThresholds',[]);

                % Thus counts on us only studying one letter size, which is
                % enforced by the options in the call above.
                keys = psychometricFunction{ss,rr,ff}.keys;
                pCorrect(ss,rr,ff) = psychometricFunction{ss,rr,ff}(keys{1});
        end
    end
end