% SpatialCSFCalcs
%
% Code that models spatial CSFs under various assumptions

%% Clear
clear; close all;

%% Get root path
options.rootPath = getpref('ISETBerkeleyAOTumblingE','dataPath');

%% Visualization
visualizeEachScene = true;
visualizeEachResponse =  true;
responseVisualizationFunction = @nreVisualizeCMosaic;
maxVisualizedNoisyResponseInstances = 8;
maxVisualizedNoisyResponseInstanceStimuli = 4;

%% Photocurrent: name of this one
options.calcName = '0Hz_500ms_duration_100ms_stim_photocurrent_nofem';

%% Set up summary filename and output dir
%
% Saving these with an options string that the user can set to denote the
% condtions.
summaryFileName = ['SpatialCSF_' options.calcName];
options.outputResultsDir = fullfile(options.rootPath,'results',summaryFileName);
options.outputFiguresDir =  fullfile(options.rootPath,'figures',summaryFileName);
if (~exist(options.outputResultsDir,'dir'))
    mkdir(options.outputResultsDir);
end
if (~exist(options.outputFiguresDir,'dir'))
    mkdir(options.outputFiguresDir);
end

 t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.02, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'nTrainEMs', 8, ...
        'nTestEMs', 8, ...
        'nTrain', 8, ...
        'nTest', 512, ...
        'testEMsMatchTrain', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 0, ...
        'stimOnFrameIndices', 1:10, ...
        'spatialFreqs', [4 8 16 32 64], ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', visualizeEachScene, ...
        'visualizeEachResponse', visualizeEachResponse, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'responseVideoFileName', options.calcName, ...
        'maxVisualizedNoisyResponseInstances', maxVisualizedNoisyResponseInstances, ...
        'maxVisualizedNoisyResponseInstanceStimuli',maxVisualizedNoisyResponseInstanceStimuli, ...
        'figureFileBase', options.outputFiguresDir, ...
        'resultsFileBase', options.outputResultsDir, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  []);

  %% Photocurrent: name of this one
options.calcName = '0Hz_500ms_duration_100ms_stim_photocurrent_withfem';

%% Set up summary filename and output dir
%
% Saving these with an options string that the user can set to denote the
% condtions.
summaryFileName = ['SpatialCSF_' options.calcName];
options.outputResultsDir = fullfile(options.rootPath,'results',summaryFileName);
options.outputFiguresDir =  fullfile(options.rootPath,'figures',summaryFileName);
if (~exist(options.outputResultsDir,'dir'))
    mkdir(options.outputResultsDir);
end
if (~exist(options.outputFiguresDir,'dir'))
    mkdir(options.outputFiguresDir);
end

 t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.02, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', true, ...
        'nTrainEMs', 8, ...
        'nTestEMs', 8, ...
        'nTrain', 8, ...
        'nTest', 512, ...
        'testEMsMatchTrain', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 0, ...
        'stimOnFrameIndices', 1:10, ...
        'spatialFreqs', [4 8 16 32 64], ...
        'temporalFilterValues', 'photocurrentImpulseResponseBased', ...
        'visualizeEachScene', visualizeEachScene, ...
        'visualizeEachResponse', visualizeEachResponse, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'responseVideoFileName', options.calcName, ...
        'maxVisualizedNoisyResponseInstances', maxVisualizedNoisyResponseInstances, ...
        'maxVisualizedNoisyResponseInstanceStimuli',maxVisualizedNoisyResponseInstanceStimuli, ...
        'figureFileBase', options.outputFiguresDir, ...
        'resultsFileBase', options.outputResultsDir, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds', []);

%% Watson: name of this one
options.calcName = '0Hz_500ms_duration_100ms_stim_watson_nofem';

%% Set up summary filename and output dir
%
% Saving these with an options string that the user can set to denote the
% condtions.
summaryFileName = ['SpatialCSF_' options.calcName];
options.outputResultsDir = fullfile(options.rootPath,'results',summaryFileName);
options.outputFiguresDir =  fullfile(options.rootPath,'figures',summaryFileName);
if (~exist(options.outputResultsDir,'dir'))
    mkdir(options.outputResultsDir);
end
if (~exist(options.outputFiguresDir,'dir'))
    mkdir(options.outputFiguresDir);
end

 t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.02, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'nTrainEMs', 8, ...
        'nTestEMs', 8, ...
        'nTrain', 8, ...
        'nTest', 512, ...
        'testEMsMatchTrain', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 0, ...
        'stimOnFrameIndices', 1:10, ...
        'spatialFreqs', [4 8 16 32 64], ...
        'temporalFilterValues', 'watsonFilter', ...
        'watsonTau', 12, ...
        'visualizeEachScene', visualizeEachScene, ...
        'visualizeEachResponse', visualizeEachResponse, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'responseVideoFileName', options.calcName, ...
        'maxVisualizedNoisyResponseInstances', maxVisualizedNoisyResponseInstances, ...
        'maxVisualizedNoisyResponseInstanceStimuli',maxVisualizedNoisyResponseInstanceStimuli, ...
       'figureFileBase', options.outputFiguresDir, ...
        'resultsFileBase', options.outputResultsDir, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  []);

 %% Watson: name of this one
options.calcName = '0Hz_500ms_duration_100ms_stim_watson_withfem';

%% Set up summary filename and output dir
%
% Saving these with an options string that the user can set to denote the
% condtions.
summaryFileName = ['SpatialCSF_' options.calcName];
options.outputResultsDir = fullfile(options.rootPath,'results',summaryFileName);
options.outputFiguresDir =  fullfile(options.rootPath,'figures',summaryFileName);
if (~exist(options.outputResultsDir,'dir'))
    mkdir(options.outputResultsDir);
end
if (~exist(options.outputFiguresDir,'dir'))
    mkdir(options.outputFiguresDir);
end

 t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.02, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', true, ...
        'nTrainEMs', 8, ...
        'nTestEMs', 8, ...
        'nTrain', 8, ...
        'nTest', 512, ...
        'testEMsMatchTrain', true, ...
        'numberOfFrames', 25, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 0, ...
        'stimOnFrameIndices', 1:10, ...
        'spatialFreqs', [4 8 16 32 64], ...
        'temporalFilterValues', 'watsonFilter', ...
        'watsonTau', 12, ...
         'visualizeEachScene', visualizeEachScene, ...
        'visualizeEachResponse', visualizeEachResponse, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'responseVideoFileName', options.calcName, ...
        'maxVisualizedNoisyResponseInstances', maxVisualizedNoisyResponseInstances, ...
        'maxVisualizedNoisyResponseInstanceStimuli',maxVisualizedNoisyResponseInstanceStimuli, ...
        'figureFileBase', options.outputFiguresDir, ...
        'resultsFileBase', options.outputResultsDir, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds', []);

 %% Watson: name of this one
options.calcName = '0Hz_500ms_duration_100ms_stim_nofilter_nofem';

%% Set up summary filename and output dir
%
% Saving these with an options string that the user can set to denote the
% condtions.
summaryFileName = ['SpatialCSF_' options.calcName];
options.outputResultsDir = fullfile(options.rootPath,'results',summaryFileName);
options.outputFiguresDir =  fullfile(options.rootPath,'figures',summaryFileName);
if (~exist(options.outputResultsDir,'dir'))
    mkdir(options.outputResultsDir);
end
if (~exist(options.outputFiguresDir,'dir'))
    mkdir(options.outputFiguresDir);
end

 t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.02, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', false, ...
        'nTrainEMs', 8, ...
        'nTestEMs', 8, ...
        'nTrain', 8, ...
        'nTest', 512, ...
        'testEMsMatchTrain', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 0, ...
        'stimOnFrameIndices', 1:10, ...
        'spatialFreqs', [4 8 16 32 64], ...
        'temporalFilterValues', '', ...
        'watsonTau', 12, ...
        'visualizeEachScene', visualizeEachScene, ...
        'visualizeEachResponse', visualizeEachResponse, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'responseVideoFileName', options.calcName, ...
        'maxVisualizedNoisyResponseInstances', maxVisualizedNoisyResponseInstances, ...
        'maxVisualizedNoisyResponseInstanceStimuli',maxVisualizedNoisyResponseInstanceStimuli, ...
       'figureFileBase', options.outputFiguresDir, ...
        'resultsFileBase', options.outputResultsDir, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds',  []);

 %% Watson: name of this one
options.calcName = '0Hz_500ms_duration_100ms_stim_nofilter_withfem';

%% Set up summary filename and output dir
%
% Saving these with an options string that the user can set to denote the
% condtions.
summaryFileName = ['SpatialCSF_' options.calcName];
options.outputResultsDir = fullfile(options.rootPath,'results',summaryFileName);
options.outputFiguresDir =  fullfile(options.rootPath,'figures',summaryFileName);
if (~exist(options.outputResultsDir,'dir'))
    mkdir(options.outputResultsDir);
end
if (~exist(options.outputFiguresDir,'dir'))
    mkdir(options.outputFiguresDir);
end

 t_spatialCSF('useMetaContrast', false, ...
        'whichNoiseFreeNre', 'excitationsCmosaic', ...
        'whichNoisyInstanceNre', 'Gaussian', ...
        'gaussianSigma', 0.02, ...
        'whichClassifierEngine', 'rceTemplateDistance', ...
        'useConeContrast', true, ...
        'useFixationalEMs', true, ...
        'nTrainEMs', 8, ...
        'nTestEMs', 8, ...
        'nTrain', 8, ...
        'nTest', 512, ...
        'testEMsMatchTrain', true, ...
        'numberOfFrames', 50, ...
        'frameDurationSeconds', 0.01, ...
        'temporalFrequencyHz', 0, ...
        'stimOnFrameIndices', 1:10, ...
        'spatialFreqs', [4 8 16 32 64], ...
        'temporalFilterValues', '', ...
        'watsonTau', 12, ...
         'visualizeEachScene', visualizeEachScene, ...
        'visualizeEachResponse', visualizeEachResponse, ...
        'responseVisualizationFunction', @nreVisualizeCMosaic, ...
        'responseVideoFileName', options.calcName, ...
        'maxVisualizedNoisyResponseInstances', maxVisualizedNoisyResponseInstances, ...
        'maxVisualizedNoisyResponseInstanceStimuli',maxVisualizedNoisyResponseInstanceStimuli, ...
        'figureFileBase', options.outputFiguresDir, ...
        'resultsFileBase', options.outputResultsDir, ...
        'oiPadMethod', 'mean', ...
        'validationThresholds', []);



